"""empty message

Revision ID: 2a2c3d95ccc0
Revises: ba13ff730060
Create Date: 2023-03-30 19:26:28.860316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2c3d95ccc0'
down_revision = 'ba13ff730060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typeURL', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_column('index')
        batch_op.drop_column('typeURL')

    # ### end Alembic commands ###
